### ISSUE TITLE
Bug: 0.4.5  and 0.4.6   crashing for older V1 model

### ISSUE THREAD

**Issue by River-Mochi** [Spagett1/PineFlash#33]
- seems to crash while getting the 2.21 files . I don't get a chance to hit update button.
- happens in light and dark mode
- happens on two different V1.
- newer pinecil V2  is no problem ( I only tested V2 yesterday so I didn't know about V1 issue). 
- crashes if I try to select  2.21, 2.20,  or 2.19.

https://user-images.githubusercontent.com/97197236/233703344-5df478c1-3c94-47e6-9536-74efd47f7d16.mp4

**Comment by TJuberg** [comment]
Confirming the same issue on Fedora 37, rpm install.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:278:70
stack backtrace:
   0:     0x563b4e80746a - std::backtrace_rs::backtrace::libunwind::trace::ha271a8a7e1f3d4ef
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x563b4e80746a - std::backtrace_rs::backtrace::trace_unsynchronized::h85739da0352c791a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563b4e80746a - std::sys_common::backtrace::_print_fmt::hbc6ebcfb2910b329
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x563b4e80746a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1c117e52d53614f
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x563b4e82e77e - core::fmt::write::h25eb51b9526b8e0c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/fmt/mod.rs:1213:17
   5:     0x563b4e800ef5 - std::io::Write::write_fmt::ha9edec5fb1621933
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/io/mod.rs:1682:15
   6:     0x563b4e807235 - std::sys_common::backtrace::_print::hf8657cd429fc3452
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x563b4e807235 - std::sys_common::backtrace::print::h41b9b18ed86f86bd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x563b4e808a1f - std::panicking::default_hook::{{closure}}::h22a91871f4454152
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:267:22
   9:     0x563b4e80875b - std::panicking::default_hook::h21ddc36de0cd4ae7
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:286:9
  10:     0x563b4e809129 - std::panicking::rust_panic_with_hook::h5059419d6d59b3d0
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:688:13
  11:     0x563b4e808ec9 - std::panicking::begin_panic_handler::{{closure}}::h0f383c291cd78343
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:579:13
  12:     0x563b4e80791c - std::sys_common::backtrace::__rust_end_short_backtrace::h70ab22f2ad318cdd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x563b4e808bd2 - rust_begin_unwind
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
  14:     0x563b4e3ee493 - core::panicking::panic_fmt::hd1d46bcde3c61d72
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
  15:     0x563b4e3ee943 - core::result::unwrap_failed::h456a23f68607268c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
  16:     0x563b4e41fae0 - <pineflash::Flasher as eframe::epi::App>::update::h293ac59ec07e5403
  17:     0x563b4e571eac - eframe::native::epi_integration::EpiIntegration::update::h4c666d7910ba73e1
  18:     0x563b4e539029 - <eframe::native::run::glow_integration::GlowWinitApp as eframe::native::run::WinitApp>::paint::h8ac2a6c2953450fd
  19:     0x563b4e547951 - eframe::native::run::run_and_return::{{closure}}::h5556733a23454560
  20:     0x563b4e521646 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration::h5b72dc6c07759acc
  21:     0x563b4e5233e9 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h93f6ea3d082dec2d
  22:     0x563b4e526864 - eframe::native::run::run_and_return::hf949393b9b82f115
  23:     0x563b4e558604 - std::thread::local::LocalKey<T>::with::h84548d716576ebd4
  24:     0x563b4e53b3ee - eframe::native::run::glow_integration::run_glow::he3182ca56c7ec2a1
  25:     0x563b4e51cdef - eframe::run_native::h60a2b0b9c14986b2
  26:     0x563b4e4209ef - pineflash::main::ha6ef224c6c292723
  27:     0x563b4e4027a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbe4dc8798dcbb015
  28:     0x563b4e407d59 - std::rt::lang_start::{{closure}}::h540820bb07cf4359
  29:     0x563b4e7fbfbc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h203afb3af230319a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:287:13
  30:     0x563b4e7fbfbc - std::panicking::try::do_call::hf68e87013b70f3c5
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  31:     0x563b4e7fbfbc - std::panicking::try::h040ea8f298390ba2
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  32:     0x563b4e7fbfbc - std::panic::catch_unwind::h1e17b198887a05fa
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  33:     0x563b4e7fbfbc - std::rt::lang_start_internal::{{closure}}::hfb902d8927e51b86
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:48
  34:     0x563b4e7fbfbc - std::panicking::try::do_call::h354e6eb41f2e7d42
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  35:     0x563b4e7fbfbc - std::panicking::try::h4a39749cd018228c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  36:     0x563b4e7fbfbc - std::panic::catch_unwind::h30bce83b8de61cca
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  37:     0x563b4e7fbfbc - std::rt::lang_start_internal::h8f7e70b1a2558118
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:20
  38:     0x563b4e420b65 - main
  39:     0x7efe1dbed510 - __libc_start_call_main
  40:     0x7efe1dbed5c9 - __libc_start_main@GLIBC_2.2.5
  41:     0x563b4e3eead5 - _start
  42:                0x0 - <unknown>
```

**Comment by Spagett1** [comment]
Sorry everyone, if you update now it should be fixed.

**Comment by Spagett1** [comment]
Apparently its not, @TJuberg could you please post logs of the 0.4.6 version? I cant reproduce a crash that @River-Mochi has told me about in dm's and since he is on windows its not possible for him to get the stack trace like you did there.

**Comment by Spagett1** [comment]
the crash has changed to later in the program so something i did fixed a bit but there is another crash at the flashing stage

**Comment by River-Mochi** [comment]
I'm using  new hot fix  4.6 now and it still crashes but  does it later.  I can't post logs since im in windows so we need to wait for  @TJuberg   or someone else that has  a V1 + linux.

**Comment by TuxThePenguin0** [comment]
Tested the latest 0.4.6 hotfix on Fedora 38 with an RPM install and after figuring out that the v1 doesn't like some of my USB ports it works fine for me.

**Comment by Spagett1** [comment]
Good to hear, after some other reports i believe its a only windows issue now

**Comment by Spagett1** [comment]
Alrighty, this should be solved with the latest release.

**Comment by River-Mochi** [comment]
> i believe its a only windows issue now

but... is it really a windows issue or a path issue? 😛

**Comment by TJuberg** [comment]
Been a busy few days, apoligies for late response.
I can confirm that 0.4.7 works as it should on Fedora with no crashing as well as on Windows 11.

**Comment by River-Mochi** [comment]
new one works on windows 11  for both V1 and V2, but I can not get it to work for V2 in MacOS.
